# spring
spring:
  data:
    mongodb:
      uri: mongodb://k4a305.p.ssafy.io:27017/27017
# mongodb
mongodb:
  test:
    connectionString: mongodb://k4a305.p.ssafy.io:27017/27017
    
server:
  port: 8877
